apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fuw9bdv98-python
  janus-idp.io/tekton: fuw9bdv98-python
  backstage.io/kubernetes-id: fuw9bdv98-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fuw9bdv98-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
